[build-system]
requires = ["setuptools>=39.2.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = [
    "ldap_auth_provider",
    "tests"
]

[tool.check-manifest]
ignore = [
    "scripts-dev/lint.sh"
]
